name: pet_adoption
description: "Felvera."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  introduction_screen: ^3.1.14
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/resim.png
